In [5]:
import dhlab as dh
import pandas as pd
import dhlab.api.dhlab_api as api

In [80]:
corpus = pd.read_csv('norske_aviser.csv', index_col = 0)

In [97]:
corpus

,dhlabid,urn,title,doctype,timestamp,year,authors,oaiid,sesamid,isbn10,city,publisher,langs,subjects,ddc,genres,literaryform
0,100039294.0,URN:NBN:no-nb_digibok_2007073004005,Av en utvandreravis' saga : Nordisk Tidende i ...,digibok,19680101.0,1968.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100003861.0,URN:NBN:no-nb_digibok_2007041901045,Av en utvandreravis' saga : Nordisk Tidende i ...,digibok,19660101.0,1966.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,203307348.0,URN:NBN:no-nb_digavis_decorahposten_null_null_...,decorahposten,digavis,19401129.0,1940.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,202125657.0,URN:NBN:no-nb_digavis_decorahposten_null_null_...,decorahposten,digavis,19700326.0,1970.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,202125057.0,URN:NBN:no-nb_digavis_decorahposten_null_null_...,decorahposten,digavis,19150611.0,1915.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,203461740.0,URN:NBN:no-nb_digavis_vinland_null_null_197307...,vinland,digavis,19730719.0,1973.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,203461629.0,URN:NBN:no-nb_digavis_vinland_null_null_197103...,vinland,digavis,19710304.0,1971.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,203461064.0,URN:NBN:no-nb_digavis_vinland_null_null_195912...,vinland,digavis,19591210.0,1959.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,203461508.0,URN:NBN:no-nb_digavis_vinland_null_null_196809...,vinland,digavis,19680905.0,1968.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,203461729.0,URN:NBN:no-nb_digavis_vinland_null_null_197305...,vinland,digavis,19730503.0,1973.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
import requests

In [114]:
r=requests.post(f"{api.BASE_URL}/frequencies", json = {'urns':list(corpus.urn.values), 'cutoff':5, 'words':['utenordmenn','og', 'i', '.']})

In [116]:
df = pd.DataFrame(r.json())

In [117]:
df.columns = ['urn', 'word', 'freq', 'doc']

In [119]:
df[df['word'] =='utenordmenn'].sum()

urn     URN:NBN:no-nb_digavis_nordisktidende_null_null...
word    utenordmennutenordmennutenordmennutenordmennut...
freq                                                    8
doc                                                382484
dtype: object